services:
  - type: web
    name: brasileirao-demo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: demo
